site_name: 5sigmas - Más señal, menos ruido
site_description: La evolución de las matemáticas, filosofía e ingeniería en el camino al AGI
site_url: "https://5sigmas.com"
theme:
  name: material
  language: es
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: cyan
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - content.code.copy
    - content.action.edit

extra:
  generator: false  # quita “Made with Material for MkDocs”
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fjmm1998/

nav:
  - Inicio: index.md
  - Series:
      - La IA, IA Generativa y AGI:
          - Presentación: series/basicos-IA-IAG/00_presentacion_serie.md
      - De las cavernas a la AGI:
          - Presentación: series/from-cave-to-AGI/00_presentacion_serie.md
      #     - "Acto I: Inventar símbolos":
      #         - "De las muescas en hueso al número, cómo nace la abstracción (< 1000 a. C.)": series/from-cave-to-AGI/1-01-muescas.md
      #     -  "El proyecto griego (1000 a. C. – año 0)": series/from-cave-to-AGI/1-02-griego.md
      #     - "Cero, álgebra y relojes (año 0 – 1500)": series/from-cave-to-AGI/1-03-cero-algebra.md
      #     - "Del cálculo al mundo como sistema dinámico (1500–1800)": series/from-cave-to-AGI/1-04-calculo-mundo.md
      # - "Acto II: Enseñar a las máquinas":
      #     - "De la mente a la máquina universal": series/from-cave-to-AGI/2-01-mente-maquina.md
      #     - "De Gotinga a Londres": series/from-cave-to-AGI/2-02-gotinga-londres.md
      #     - "Primeras neuronas de metal": series/from-cave-to-AGI/2-03-neuronas-metal.md
      # - "Acto III: Escalar el aprendizaje":
      #     - "WW qué?!": series/from-cave-to-AGI/3-01-ww-que.md
      #     - "Primeras neuronas parlantes": series/from-cave-to-AGI/3-02-neuronas-parlantes.md
      #     - "¿Modelos que «razonan»?": series/from-cave-to-AGI/3-03-modelos-razonan.md
      #     - "Modelos del mundo": series/from-cave-to-AGI/3-04-modelos-mundo.md
      #     - "Nuevas arquitecturas": Hablar de Titans, de Nested learning y el cambio de paradigma que suponen
      # - La felicidad, estado de bienestar y energía: series/happiness-welfare-energy/index.md
  - Sobre mí: meta/about.md
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true   # hace que MathJax procese los bloques marcados
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/external-links.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros
  # - blog        # optional – see below
